### PR TITLE
Fix UI issue occurring while opening assignee modal

### LINKED ISSUE #218: On expanding the RHS completely and opening the assigning modal hampers the UI
**Steps to reproduce:-**
1. Expand the RHS fully.
2. Create a todo task and open the assignee modal.

The assign modal hampers the UI of MM.
(verify from the image below)

image

Also the action behind the dull area on the screen can not be performed, but the actions in the brighter area can be.

### PR DESCRIPTION
**Pull request by ayusht2810**
#### Summary
Fixed UI issue occurring while opening assignee modal

#### Ticket Link
Fixes #218 

#### Screenshot
image

#### Checklist
- [x] Completed dev testing
- [x] `make test` Ran test cases and ensured they are passing
- [x] `make check-style` Ran style check and ensured both webapp and server pass the checks

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
@ayusht2810 Updating the branch with master should fix any playwright CI errors

**Review by raghavaggarwal2308 — APPROVED** [review]

**Comment by AayushChaudhary0001** [comment]
This PR was tested for the UI hampering of the MM if the RHS is expanded fully. 

But I am facing an issue here like if we click on the background area when the modal is opened and RHS is fully expanded, the RHS behind closes despite of that area being inactive.

Steps to reproduce:-
1. Expand the RHS and open the modal.
2. Click on the area behind the modal.

The RHS gets closed, which is not consistent for all the other plugins. Please have a look if we can handle this.
cc: @mickmister

**Comment by raghavaggarwal2308** [comment]
@AayushChaudhary0001 The above issue seems to be a very rare edge case. Can you please create a separate issue for that?

**Comment by AayushChaudhary0001** [comment]
@raghavaggarwal2308 I have created a seperate issue for this(https://github.com/mattermost-community/mattermost-plugin-todo/issues/260). Approving this PR for now.

**Review by AayushChaudhary0001 — APPROVED** [review]

**Pull request merged**
